const express = require('express');
const router = express.Router();

// Import route files
const roleRoutes = require('./auth/roleRoutes.js');
const userRoutes = require('./auth/userRoutes.js');
const agentRoutes = require('./auth/agentRoutes.js');
const authRoutes = require('./auth/authRoutes.js');
const categoryRoutes = require('./category/categoryRoutes.js');
const segmentRoutes = require('./segment/segmentRoutes.js');
const bankAccountsRoutes = require('./banks/bankAccountRoutes.js');
const bankRoutes = require('./banks/bankRoutes.js');
const feesRoutes = require('./fees/feesRoutes.js');
const providerRoutes = require('./provider/provideRoutes.js');
const providerCommissionRoutes = require('./provider/providerCommissionRoutes');
const appsRoutes = require('./applications/applicationRoutes.js');
const transactionRoutes = require('./transaction/transactionRoutes.js');
const depositeRoutes = require('./transaction/depositeRoutes.js');
const withdrawRoutes = require('./transaction/withdrawRoutes.js');
const transferRoutes = require('./transaction/transferRoutes.js');
const commissionRoutes = require('./commisssion/commissionRoutes.js');
const inventoryRoutes = require('./inventory/inventoryRoutes.js');
const reportsRoutes = require('./Reports/reportsRoutes.js');
const agentTreasuryRoutes = require('./agentTreasury/agentTreasuryRoutes.js');
const providerTreasuryRoutes = require('./providerTreasury/providerTreasuryRoutes.js');
const addionalTreasuryRoutes = require('./addionalTreasury/agentTreasuryRoutes.js');
const profitsRoutes = require('./profits/profitRoutes.js');

router.use('/role', roleRoutes);
router.use('/user', userRoutes);
router.use('/agent', agentRoutes);
router.use('/auth', authRoutes);
router.use('/category', categoryRoutes);
router.use('/segment', segmentRoutes);
router.use('/banks', bankRoutes);
router.use('/bank-accounts', bankAccountsRoutes);
router.use('/transaction', transactionRoutes);
router.use('/transaction/deposite', depositeRoutes);
router.use('/transaction/withdraw', withdrawRoutes);
router.use('/transaction/transfer', transferRoutes);
router.use('/fees', feesRoutes);
router.use('/apps', appsRoutes);
router.use('/provider', providerRoutes);
router.use('/provider/commission', providerCommissionRoutes);
router.use('/commission', commissionRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/reports', reportsRoutes);
router.use('/agentTreasury', agentTreasuryRoutes);
router.use('/providerTreasury', providerTreasuryRoutes);
router.use('/addionalTreasury', addionalTreasuryRoutes);
router.use('/profits', profitsRoutes);

module.exports = router;
