const express = require('express');
const router = express.Router();

// Import route files
const roleRoutes = require('./roleRoutes');
const userRoutes = require('./userRoutes');
const agentRoutes = require('./auth/agentRoutes');
const authRoutes = require('./authRoutes');
const categoriesRoutes = require('./categoryRoutes');
const subCategoriesRoutes = require('./subCategoryRoutes');
const segmentRoutes = require('./segmentRoutes');
const bankAccountsRoutes = require('./bankAccountRoutes');
const bankRoutes = require('./bankRoutes');
const feesRoutes = require('./feesRoutes');
const providerRoutes = require('./provideRoutes');
const providerCommissionRoutes = require('./providerCommissionRoutes');
const appsRoutes = require('./applicationRoutes');
const transactionRoutes = require('./transaction/transactionRoutes');
const depositeRoutes = require('./transaction/depositeRoutes');
const withdrawRoutes = require('./transaction/withdrawRoutes');
const transferRoutes = require('./transferRoutes');
const commissionRoutes = require('./commisssion/commissionRoutes');
const inventoryRoutes = require('./inventory/inventoryRoutes');
const reportsRoutes = require('./Reports/reportsRoutes');
const agentTreasuryRoutes = require('./agentTreasuryRoutes');
const providerTreasuryRoutes = require('./providerTreasuryRoutes');
const duesRoutes = require('./duesRoutes');
const addionalTreasuryRoutes = require('./addionalTreasuryRoutes');
const profitsRoutes = require('./profits/profitRoutes');
const chatRoutes = require('./chat/chatRoute');

router.use('/roles', roleRoutes);
router.use('/users', userRoutes);
// router.use('/agent', agentRoutes);
router.use('/auth', authRoutes);
router.use('/categories', categoriesRoutes);
router.use('/subCategories', subCategoriesRoutes);
router.use('/segments', segmentRoutes);
router.use('/banks', bankRoutes);
router.use('/bank-accounts', bankAccountsRoutes);
router.use('/transactions', transactionRoutes);
router.use('/transaction/deposite', depositeRoutes);
router.use('/transaction/withdraw', withdrawRoutes);
router.use('/transfers', transferRoutes);
router.use('/fees', feesRoutes);
router.use('/apps', appsRoutes);
router.use('/providers', providerRoutes);
router.use('/providers-commissions', providerCommissionRoutes);
router.use('/commission', commissionRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/reports', reportsRoutes);
router.use('/agentTreasuries', agentTreasuryRoutes);
router.use('/providerTreasuries', providerTreasuryRoutes);
router.use('/addionalTreasuries', addionalTreasuryRoutes);
router.use('/dues', duesRoutes);
router.use('/profits', profitsRoutes);
router.use('/chat', chatRoutes);

module.exports = router;
